const speakers = [
  {
    id: 0,
    name: "Ankush Singla",
    img: "/Speakers/ankur.jpg",
    post: "Co-Founder, Coding Ninjas",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.linkedin.com/in/ankushsingla",
  },
  {
    id: 1,
    name: "Anuj Batra",
    img: "/Speakers/anuj.jpg",
    post: "Co-Founder, Andromedia Maritime Solutions",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.linkedin.com/in/anujbatra1/",
  },
  {
    id: 2,
    name: "Ashish Meena",
    img: "/Speakers/ashishMeena.jpg",
    post: "Vice President of technology, OYO rickshaw",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.linkedin.com/in/ashishmeena8/",
  },
  {
    id: 3,
    name: "Aashish Sharma",
    img: "/Speakers/ashish.png",
    post: "Vice President, Capgemini",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.linkedin.com/in/aashishsharma1/",
  },
  {
    id: 4,
    name: "Amit Yadav",
    img: "/Speakers/amityadav.jpeg",
    post: "D2C Product & Growth @ Mamaearth ",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.linkedin.com/in/amit-at-8287502355/",
  },
  {
    id: 5,
    name: "Ganesh Kumar",
    img: "/Speakers/ganesh.jpg",
    post: "City Head, Shadowfax",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.linkedin.com/in/ganesh-kumar-9317bb7/",
  },
  {
    id: 6,
    name: "Navin Manaswi",
    img: "/Speakers/navin.jpg",
    post: "Founder and CEO, WoWexp Technologies",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.linkedin.com/in/navin-manaswi-1a708b8",
  },
  {
    id: 7,
    name: "R K Guran",
    img: "/Speakers/rk.jpg",
    post: "Founder, StartupCasa",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.linkedin.com/in/rakesh-kumar-guran-rkg",
  },
  {
    id: 8,
    name: "shivesh kumar",
    img: "/Speakers/shivesh.jpg",
    post: "Founder and CEO, StartUp Monk",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.linkedin.com/in/siveshkumar",
  },
  {
    id: 9,
    name: "Snehaal Dhruv",
    img: "/Speakers/snehal.jpg",
    post: "Co-founder & CEO, Superfan Studio",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.linkedin.com/in/snehaaldhruv",
  },
  {
    id: 10,
    name: "Tapan Singhel",
    img: "/Speakers/tapan.jpg",
    post: "Managing Director & CEO, Bajaj Allianz General Insurance",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.linkedin.com/in/tapansinghel/",
  },
  {
    id: 11,
    name: "Utkarsh Shukla",
    img: "/Speakers/utkarsh.jpg",
    post: "Founder, CEO, YUG Metaverse",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.linkedin.com/in/utkarshx",
  },
  {
    id: 12,
    name: "Vikas Bansal",
    img: "/Speakers/vikas.jpg",
    post: "Co-Founder, Crejo.Fun",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.linkedin.com/in/vikasbansal",
  }
];

export default speakers;
