const speakers = [
  {
    id: 0,
    name: "Kishan Tiwari",
    img: "/Speakers/kishan.png",
    post: "Founder and CEO \n TSAW Drones and Droneco",
    facebook: "https://www.facebook.com/manish.advani.12",
    twitter: "https://twitter.com/IndianMarketer",
    linkedIn: "https://www.linkedin.com/in/kishan-thedroneco/",
  },
  {
    id: 1,
    name: "Vijay Sharma",
    img: "/Speakers/vijay.png",
    post: "Co-founder and CTO \n Silver Oak Health",
    facebook: "https://www.facebook.com/neha.mi.agrawal",
    twitter: "https://twitter.com/NehaAgrawalMath",
    linkedIn: "https://www.linkedin.com/in/mrvijaysharma/",
  },
  {
    id: 2,
    name: "Nabin Roy",
    img: "/Speakers/nabin.png",
    post: "Founder Canvas Workspace | YC S’19",
    facebook: "https://www.facebook.com/MananVermaTech",
    twitter: "https://twitter.com/MananVermaTech",
    linkedIn: "https://www.linkedin.com/in/nabinroy/",
  },
  {
    id: 3,
    name: "Anugrah Agnihotri",
    img: "/Speakers/anug.png",
    post: "Founder Dot",
    facebook: "https://www.facebook.com/skjsaurabh",
    twitter: "https://twitter.com/skjsaurabh",
    linkedIn: "https://www.linkedin.com/in/anugrah-agnihotri/",
  },
  {
    id: 4,
    name: "Saloni Malhotra",
    img: "/Speakers/saloni.png",
    post: "Product Management",
    facebook: "https://www.facebook.com/bjethani",
    twitter: "https://twitter.com/JethaniBharat",
    linkedIn: "https://www.linkedin.com/in/saloni-malhotra/",
  },
  {
    id: 5,
    name: "Sasikanth R",
    img: "/Speakers/sashikant.png",
    post: "Board Member Aye2Zee Venture Consultancy",
    facebook: "https://www.facebook.com/jagat.iyer",
    twitter: "https://twitter.com/vidphone",
    linkedIn: "https://www.linkedin.com/in/sasikanthr/",
  },
  {
    id: 6,
    name: "Jagriti Kesarwani",
    img: "/Speakers/Jagriti.jpg",
    post: "Influencer | Program Manager Google",
    facebook: "https://www.instagram.com/harshaksinha/",
    twitter: "https://twitter.com/HarshakSinha",
    linkedIn: "https://www.instagram.com/jagritikesarwani",
  },
  {
    id: 7,
    name: "Aditya Saini",
    img: "/Speakers/aditya.png",
    post: "Finance Content Creator, Youtuber",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.youtube.com/@theadityasaini",
  },
  {
    id: 8,
    name: "Yash Pratap Singh",
    img: "/Speakers/yash.png",
    post: "Business/Startups Youtuber",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://youtube.com/@yashpratapsingh_0001?si=DGHDnnKyMH9OeHfO",
  },
  {
    id: 9,
    name: "Mack Vocals",
    img: "/Speakers/mack.png",
    post: "Singer",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.instagram.com/mackvocals/",
  },
  {
    id: 10,
    name: "Dr. Vijender Singh Chauhan",
    img: "/Speakers/vij.jpg",
    post: "Lecturer",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.linkedin.com/in/vijendermasijeevi/",
  },
  {
    id: 11,
    name: "Acyuta Mohan Das",
    img: "/Speakers/acy.png",
    post: "President ISKCON, Prayagraj",
    facebook: "https://www.facebook.com/mnnitecell",
    twitter: "https://twitter.com/ecellmnnit",
    linkedIn: "https://www.linkedin.com/in/acyuta-mohan-das-4450541a7/",
  },
  
];

export default speakers;
